resource "aws_s3_bucket" "trivy_reports" {
  # checkov:skip=CKV_AWS_144:Cross-region replication is unnecessary for 90-day scan reports that can be regenerated by CI
  # checkov:skip=CKV2_AWS_62:No downstream consumer for S3 event notifications in this pipeline
  bucket = "${var.project_name}-trivy-reports"

  tags = {
    Name = "${var.project_name}-trivy-reports"
  }
}

# Replace your existing encryption resource with this one
resource "aws_s3_bucket_server_side_encryption_configuration" "trivy_reports" {
  bucket = aws_s3_bucket.trivy_reports.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.main.arn
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_logging" "trivy_reports" {
  bucket        = aws_s3_bucket.trivy_reports.id
  target_bucket = aws_s3_bucket.access_logs.id
  target_prefix = "trivy-reports/"
}

resource "aws_s3_bucket_versioning" "trivy_reports" {
  bucket = aws_s3_bucket.trivy_reports.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "trivy_reports" {
  bucket                  = aws_s3_bucket.trivy_reports.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "trivy_reports" {
  bucket = aws_s3_bucket.trivy_reports.id

  rule {
    id     = "expire-old-reports"
    status = "Enabled"

    filter {}

    expiration {
      days = 90
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

# ---------- Access log bucket ----------
resource "aws_s3_bucket" "access_logs" {
  # checkov:skip=CKV_AWS_18:This is the log destination; logging itself would be circular
  # checkov:skip=CKV_AWS_144:Replication not needed for access logs in this project
  # checkov:skip=CKV2_AWS_62:No event consumers needed
  # checkov:skip=CKV_AWS_145:S3 server access log targets only support SSE-S3, not KMS
  bucket = "${var.project_name}-access-logs"
}

resource "aws_s3_bucket_public_access_block" "access_logs" {
  bucket                  = aws_s3_bucket.access_logs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "access_logs" {
  bucket = aws_s3_bucket.access_logs.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "access_logs" {
  bucket = aws_s3_bucket.access_logs.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "access_logs" {
  bucket = aws_s3_bucket.access_logs.id

  rule {
    id     = "expire-logs"
    status = "Enabled"

    filter {}

    expiration {
      days = 90
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

resource "aws_s3_bucket_policy" "access_logs" {
  bucket = aws_s3_bucket.access_logs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowS3LogDelivery"
        Effect    = "Allow"
        Principal = { Service = "logging.s3.amazonaws.com" }
        Action    = "s3:PutObject"
        Resource  = "${aws_s3_bucket.access_logs.arn}/*"
        Condition = {
          ArnLike      = { "aws:SourceArn" = aws_s3_bucket.trivy_reports.arn }
          StringEquals = { "aws:SourceAccount" = data.aws_caller_identity.current.account_id }
        }
      }
    ]
  })
}