name: Cloud Security CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t cloud-security-ci:${{ github.sha }} .

      - name: Debug installed package versions
        run: |
          docker --rm cloud-security-ci:${{ github.sha }}  apt-cache policy gzip libpcre2-8-0 libsqlite3-0 perl-base    

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cloud-security-ci:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true

  test:
    name: Test Application
    needs: container-security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
          pip install pip-audit

      - name: Run code quality checks
        run: |
          ruff check .

      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest
